#!/bin/sh 
#apt install zram-config
#wget -O /usr/bin/init-zram-swapping https://raw.githubusercontent.com/SlavaGavrilin/zram/main/init-zram-swapping
#systemctl restart zram-config

# load dependency modules 
NRDEVICES=$(nproc) 
if modinfo zram | grep -q ' zram_num_devices:' 2>/dev/null; then 
 MODPROBE_ARGS="zram_num_devices=${NRDEVICES}" 
elif modinfo zram | grep -q ' num_devices:' 2>/dev/null; then 
 MODPROBE_ARGS="num_devices=${NRDEVICES}" 
else 
 exit 1 
fi 
modprobe zram $MODPROBE_ARGS 

# Calculate memory to use for zram (3/4 of ram) 
totalmem=`free|head -n +2|tail -n1|awk {'print $2'}` 
mem=$(((totalmem / 4 * 3 / ${NRDEVICES}) * 1024)) 

# initialize the devices 
for i in $(seq ${NRDEVICES}); do 
DEVNUMBER=$((i - 1)) 
 if [ -b /dev/zram${DEVNUMBER} ];then 
  if [ $(swapon -s|grep /dev/zram${DEVNUMBER}|wc -l) -gt 0 ];then  
   swapoff /dev/zram${DEVNUMBER}
   echo 1 > /sys/block/zram${DEVNUMBER}/reset 
  fi 
 else 
  cat /sys/class/zram-control/hot_add 
 fi 
 echo lz4  > /sys/block/zram${DEVNUMBER}/comp_algorithm
 echo $mem > /sys/block/zram${DEVNUMBER}/disksize 
 mkswap /dev/zram${DEVNUMBER} 
 swapon -p 5 /dev/zram${DEVNUMBER} 
done 
#swap actively to use zram
sysctl -w vm.swappiness=95 
